# Generated by Django 4.2.24 on 2025-09-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_job_jobapplication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="job_title",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="job_description",
            new_name="description",
        ),
        migrations.AddField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                choices=[("Full-time", "Full-time"), ("Contract", "Contract")],
                default="Full-time",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="Doha", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.CharField(default="Title", max_length=255),
            preserve_default=False,
        ),
    ]
