# Generated by Django 4.2.24 on 2025-09-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_usercv_jobapplication_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
