# Generated by Django 4.2.24 on 2025-09-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_jobapplication_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercv",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
