name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Lint with flake8
        run: |
          poetry run flake8 .

      - name: Build (check migrations and collectstatic)
        run: |
          poetry run python manage.py check
          poetry run python manage.py makemigrations --check --dry-run
          poetry run python manage.py collectstatic --noinput

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-lint
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t jobmatch-backend:ci .
